"""empty message

Revision ID: 548b567cae0b
Revises: a18139c5f27c
Create Date: 2024-05-19 05:05:48.679334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548b567cae0b'
down_revision = 'a18139c5f27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admiin', schema=None) as batch_op:
        batch_op.drop_constraint('admiin_password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admiin', schema=None) as batch_op:
        batch_op.create_unique_constraint('admiin_password_key', ['password'])

    # ### end Alembic commands ###
